In [2]:
import sqlite3
import pandas as pd

In [3]:
conn = sqlite3.connect("employee_db.db")
cursor = conn.cursor()

print("Database Connected Successfully")

Database Connected Successfully

In [4]:
cursor.execute("""
CREATE TABLE Employees (
    EmpID INTEGER PRIMARY KEY,
    EmpName TEXT,
    Department TEXT,
    City TEXT,
    Salary INTEGER,
    HireDate DATE
)
""")

print("Employees Table Created Successfully")

Employees Table Created Successfully

In [5]:
employees = [
(101,'Rahul Mehta','Sales','Delhi',55000,'2020-04-12'),
(102,'Priya Sharma','HR','Mumbai',62000,'2019-09-25'),
(103,'Aman Singh','IT','Bengaluru',72000,'2021-03-10'),
(104,'Neha Patel','Sales','Delhi',48000,'2022-01-14'),
(105,'Karan Joshi','Marketing','Pune',45000,'2018-07-22'),
(106,'Divya Nair','IT','Chennai',81000,'2019-12-11'),
(107,'Raj Kumar','HR','Delhi',60000,'2020-05-28'),
(108,'Simran Kaur','Finance','Mumbai',58000,'2021-08-03'),
(109,'Arjun Reddy','IT','Hyderabad',70000,'2022-02-18'),
(110,'Anjali Das','Sales','Kolkata',51000,'2023-01-15')
]

cursor.executemany("""
INSERT INTO Employees
VALUES (?,?,?,?,?,?)
""", employees)

conn.commit()

print("Data Inserted Successfully")

Data Inserted Successfully

#Question 1
Show employees working in either the IT or HR departments.

In [7]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE Department IN ('IT','HR')
""", conn)

df

   EmpID       EmpName Department       City  Salary    HireDate
0    102  Priya Sharma         HR     Mumbai   62000  2019-09-25
1    103    Aman Singh         IT  Bengaluru   72000  2021-03-10
2    106    Divya Nair         IT    Chennai   81000  2019-12-11
3    107     Raj Kumar         HR      Delhi   60000  2020-05-28
4    109   Arjun Reddy         IT  Hyderabad   70000  2022-02-18

#Question 2
Retrieve employees whose department is Sales, IT or Finance.

In [8]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE Department IN ('Sales','IT','Finance')
""", conn)

df

   EmpID      EmpName Department       City  Salary    HireDate
0    101  Rahul Mehta      Sales      Delhi   55000  2020-04-12
1    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
2    104   Neha Patel      Sales      Delhi   48000  2022-01-14
3    106   Divya Nair         IT    Chennai   81000  2019-12-11
4    108  Simran Kaur    Finance     Mumbai   58000  2021-08-03
5    109  Arjun Reddy         IT  Hyderabad   70000  2022-02-18
6    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

#Question 3
Display employees whose salary is between ₹50,000 and ₹70,000.

In [9]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE Salary BETWEEN 50000 AND 70000
""", conn)

df

   EmpID       EmpName Department       City  Salary    HireDate
0    101   Rahul Mehta      Sales      Delhi   55000  2020-04-12
1    102  Priya Sharma         HR     Mumbai   62000  2019-09-25
2    107     Raj Kumar         HR      Delhi   60000  2020-05-28
3    108   Simran Kaur    Finance     Mumbai   58000  2021-08-03
4    109   Arjun Reddy         IT  Hyderabad   70000  2022-02-18
5    110    Anjali Das      Sales    Kolkata   51000  2023-01-15

#Question 4
List employees whose names start with the letter A.

In [10]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE EmpName LIKE 'A%'
""", conn)

df

   EmpID      EmpName Department       City  Salary    HireDate
0    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
1    109  Arjun Reddy         IT  Hyderabad   70000  2022-02-18
2    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

#Question 5
Find employees whose names contain the substring "an".

In [11]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE EmpName LIKE '%an%'
""", conn)

df

   EmpID      EmpName Department       City  Salary    HireDate
0    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
1    105  Karan Joshi  Marketing       Pune   45000  2018-07-22
2    108  Simran Kaur    Finance     Mumbai   58000  2021-08-03
3    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

#Question 6
Show employees who are from Delhi or Mumbai and earn more than ₹55,000.

In [12]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE City IN ('Delhi','Mumbai')
AND Salary > 55000
""", conn)

df

   EmpID       EmpName Department    City  Salary    HireDate
0    102  Priya Sharma         HR  Mumbai   62000  2019-09-25
1    107     Raj Kumar         HR   Delhi   60000  2020-05-28
2    108   Simran Kaur    Finance  Mumbai   58000  2021-08-03

#Question 7
Display all employees except those from the HR department.

In [13]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE Department <> 'HR'
""", conn)

df

   EmpID      EmpName Department       City  Salary    HireDate
0    101  Rahul Mehta      Sales      Delhi   55000  2020-04-12
1    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
2    104   Neha Patel      Sales      Delhi   48000  2022-01-14
3    105  Karan Joshi  Marketing       Pune   45000  2018-07-22
4    106   Divya Nair         IT    Chennai   81000  2019-12-11
5    108  Simran Kaur    Finance     Mumbai   58000  2021-08-03
6    109  Arjun Reddy         IT  Hyderabad   70000  2022-02-18
7    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

#Question 8
Get all employees hired between 2019 and 2022 ordered by HireDate (oldest first).

In [14]:
df = pd.read_sql_query("""
SELECT *
FROM Employees
WHERE HireDate BETWEEN '2019-01-01' AND '2022-12-31'
ORDER BY HireDate ASC
""", conn)

df

   EmpID       EmpName Department       City  Salary    HireDate
0    102  Priya Sharma         HR     Mumbai   62000  2019-09-25
1    106    Divya Nair         IT    Chennai   81000  2019-12-11
2    101   Rahul Mehta      Sales      Delhi   55000  2020-04-12
3    107     Raj Kumar         HR      Delhi   60000  2020-05-28
4    103    Aman Singh         IT  Bengaluru   72000  2021-03-10
5    108   Simran Kaur    Finance     Mumbai   58000  2021-08-03
6    104    Neha Patel      Sales      Delhi   48000  2022-01-14
7    109   Arjun Reddy         IT  Hyderabad   70000  2022-02-18